[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "social_modules"
version = "0.1.8"
authors = [
  { name="fernand0", email="fernand0@elmundoesimperfecto.com" },
]
description = "A package to manage interaction with several social sites"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU GENERAL PUBLIC License",
    "Operating System :: OS Independent",
]
dependencies = [ 
		'colorama',
		'twitter',
		'facebook-sdk',
		'requests',
		'bs4',
		'lxml',
		'dateparser',
		'google-api-python-client',
		'google-auth-oauthlib',
		'oauth2',
		'oauth2client',
		'distance',
		'sievelib',
		'gitpython',
		'keyring',
		'click',
		'feedparser',
		'pdfrw',
		'python-crontab',
		'tmdbsimple',
		'imgurpython',
		'python-linkedin-v2@git+http://git@github.com/fernand0/python-linkedin-v2.git',
		'Mastodon.py',
		'medium',
		'pocket-api',
		'pytumblr',
		'telepot',
		'textract',
		'gitterpy',
		'slack_sdk',
		'Pillow',
		'readability-lxml'
]

[project.urls]
"Homepage" = "https://github.com/fernand0/socialModules"
"Bug Tracker" = "https://github.com/fernand0/socialModules/issues"
